---
name: Build and publish image to Docker Hub
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish-pantheon-wp-deploy-image:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{raw}}
            type=semver,pattern={{major}}
            type=semver,pattern={{version}}
            type=sha
            type=raw,enable=true,value=latest
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: image
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}